'Analizador de Entrada dw dados'
print('#' *40)
print('Analizador de Entrada de dados')
print('#' *40)
n = (input ('Digite algo: ')) 
print(type(n))
import time
time.sleep(1)
print('É número? ')
print(n.isnumeric())
print('_' *40)
time.sleep(1)
print('É alfanumérico?')
print(n.isalnum())
print('_' *40)
time.sleep(1)
print('Esta em Maiúsculo?')
print(n.isupper())
print('_' *40)
time.sleep(1)
print('Esta em Minúsculo?')
print(n.islower())
print('_' *40)
time.sleep(1)
print('É digito?')
print(n.isdigit())
print('_' *40)
time.sleep(1)
print('É alfabetico? Sao apenas letras?')
print(n.isalpha())
print('_' *40)
print(' ' *40)
print(n)
print(' ' *40)
print('_' *40)
import os
os.system('date')
print ('-------------------------------------------------')
print ( 'PAULO ROBERTO LEAL 2020')
print ('paulorleal011291@hotmail.com')
print ('-------------------------------------------------')

