print('')
print('_' *40)
print('Calculo de Boleto')
print('_' *40)
print('')
i = float(input('Digite o Valor Inicial:\n R$ '))
d = float(input('Digite o Desconto:\n(%) '))
ds = i - ((i * d) / 100)
print(ds)
print('')
print('_' *35)
a = float(input('Digite o Valor do Acréscimo:\n(%) '))
ac = ds + ((i * a) / 100)
print(ac)
print('_' *35)
m = float(input('Digite o Valor da Multa ou 0 :\n '))
print('')
print('_' *35)
mdv = float(input('Digite o Valor da Multa Diária:\n R$ '))
mdd = float(input('Digite o Número de Dias : \n '))
print('')
print('_' *35)
md = mdv * mdd
f = ac + m + md
print('#' *35)
print('O valor Devido é R$ {:.2f} '.format(f))
print('#' *35)
print('')
print('-' *35)
print('Paulo R Leal 2020 02 03')
print('paulorleal011291@hotmail.com')
print('-' * 35)