'Contador de Moedas'
print('#' * 40)
import time
print('Contafor de Moedas')
print('Paulo Roberto Leal 27/01/2020')
time.sleep(1)
c1 = input('Quantas de Moedas de 1 Centavo : ')
print(c1)
c5 = input('Quantas de Moedas de 5 Centavos: ')
print(c5)
c10 = input('Quantas de Moedas de 10 Centavos: ')
print(c10)
c25 = input('Quantas de Moedas de 25 Centavos: ')
print(25)
c50 = input('Quanta de Moedas de 50 Centavos: ')
print(50)
r = input('Quanta de Moedas de 1 Real: ')
print(r)
print('Foi digitado, {} Moedas de 1 Centavos'.format(c1))
print('Foi digitado, {} Moedas de 5 Centavos'.format(c5))
print('Foi digitado, {} Moedas de 10 Centavos'.format(c10))
print('Foi digitado, {} Moedas de 25 Centavos'.format(c25))
print('Foi digitado, {} Moedas de 50 Centavos'.format(c50))
print('Foi digitado, {} Moedas de 1 Real'.format(r))
c1t = 0.01 * float(c1)
c5t = float(0.05) * float(c5)
c10t = float(0.1) * float(c10)
c25t = float(0.25) * float(c25)
c50t = float(0.5) * float(c50)
rer = float(1) *float(r)
t = (c1t + c10t + c25t + c50t + rer)
time.sleep(1)
print(t)
time.sleep(1)
print('_' *50)
print('Total R$ {:.2f} Moedas de 1 Centavos'.format(c1t))
time.sleep(1)
print('Total R$ {:.2f} Moedas de 1 Centavos'.format(c5t))
time.sleep(1)
print('Total R$ {:.2f} Moedas de 1 Centavos'.format(c10t))
time.sleep(1)
print('Total R$ {:.2f} Moedas de 1 Centavos'.format(c25t))
time.sleep(1)
print('Total R$ {:.2f} Moedas de 1 Centavos'.format(c50t))
time.sleep(2)
print('Total R$ {:.2f} Moedas de 1 Centavos'.format(rer))
print('_' *50)
print('############################################')
print('VALOR TOTAL - SOMADAS TODAS AS MOESDAS')
print('            ***** R$ {:.2f}  *****              '.format(t))
print('############################################')
print('-' *50)
print('Paulo Roberto Leal  2020')
print('paulorleal011291@hotmail.com')

