'____Curso de Python_____'
'____Paulo Roberto Leal____'
'____Exercicio_004____'
print('Análise de Dados Tipos Primitivos ')
print('_' *40)
a = input('Digite Algo: \n')
print('_' *40)
print('O tipo deste Valor é: ',type(a))
print('_' *40)
print(' O valor é apenas espaços? ',a.isspace())
print(' O valor é um Número? ' ,a.isnumeric())
print(' O valor é Alfanumerico? ',a.isalnum())
print(' O valor é Alfabetico?' ,a.isalpha())
print(' O valor está em MAIUSCULAS? ',a.isupper())
print(' O valor está em minusculas? ',a.islower())
print(' O valor está em Capitalizado? ',a.istitle())
print('_' *40)
print('')
print('')
print(' tipos Primitivos podem ser:')
print(' _int_ - para números interiros ')
print(' _str_ - para conjuto de caracteres')
print(' _bool_ - armazena se e verdadeiro ou falso')
print(' _list_ - para agrupar um conjunto de elementos')
print(' _tupla_ - semelhate a list_  porem imutavel')
print(' _dic_ agrupa elementos que serāo recuperados \n por uma chave')
print('')
print('')
print('-' *35)
print(' Paulo Roberto Leal 2020 01 29')
print(' paulorleal011291@hotmail.com')
print('-' *35)
