'Primeira lei de Ohm'
print('#' * 40)
import time
print('Primeira lei de Ohm - Calculo de Tensão')
print('Paulo Roberto Leal 24/01/2020')
time.sleep(1)
C = input('Digite o valor da Corrente: ')
print('o numero digitado foi, {} Amperes'.format(C))
time.sleep(1)
R = input('Digite o valor da Resistência: ')
print('O Númmero digitado foi, {}, Ohms '.format(R))
time.sleep(1)
volt = float(C) * float(R)
time.sleep(1)
print('Para uma Corrente de, {}, com a Resistencia de , {} \n a Tensão será {} '.format(C,R,volt))
print('                   , {} '.format(volt))
time.sleep(2)
print('                   Resistencia em Ohm')
print('      ---------/////,{},Ohm////----------'.format(R))
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('+ --------, {},V             , {},A_|_'.format(volt,C))
print('                                          -')
print('-   ---                                   |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     --------------------------------------')
print('_' *50)
time.sleep(5)
print ('-------------------------------------------------')
print ( 'PAULO ROBERTO LEAL 2020')
print ('paulorleal011291@hotmail.com')
print ('-------------------------------------------------')
