'Primeira lei de Ohm'
print('#' * 40)
import time
print('Primeira lei de Ohm - Calculo de Corrente')
print('Paulo Roberto Leal 25/01/2020')
time.sleep(1)
T = input('Digite o valor da Tensão: ')
print('o numero digitado foi, {} Volts'.format(T))
time.sleep(1)
C = input('Digite o valor da Corrente: ')
print('O Númmero digitado foi, {}, Amperes '.format(C))
time.sleep(1)
ohm = float(T) / float(C)
time.sleep(1)
print('Para uma Tensão de, {}, com a Corrente de , {} \n a Resistência será {} '.format(T,C,ohm))
print('                   , {} '.format(ohm))
time.sleep(2)
print('                   Resistencia em Ohm')
print('      ---------/////,{},Ohm////----------'.format(ohm))
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('+ --------, {},V             , {},A_|_'.format(T,C))
print('                                          -')
print('-   ---                                   |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     --------------------------------------')
print('_' *50)
time.sleep(5)
print ('-------------------------------------------------')
print ( 'PAULO ROBERTO LEAL 2020')
print ('paulorleal011291@hotmail.com')
print ('-------------------------------------------------')
