'Primeira lei de Ohm'
print('#' * 40)
import time
print('Primeira lei de Ohm - Calculo de Corrente')
print('Paulo Roberto Leal 24/01/2020')
time.sleep(1)
T = input('Digite o valor da Tensão: ')
print('o numero digitado foi, {} Volts'.format(T))
time.sleep(1)
R = input('Digite o valor da Resistência: ')
print('O Númmero digitado foi, {}, Ohms '.format(R))
time.sleep(1)
amp = float(T) / float(R)
time.sleep(1)
print('Para uma Tensão de, {}, com a Resistencia de , {} \n a Corrente será {} '.format(T,R,amp))
print('                   , {} '.format(T))
time.sleep(2)
print('                   Resistencia em Ohm')
print('      ---------/////,{},Ohm////----------'.format(R))
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('+ --------, {},V             , {},A_|_'.format(T,amp))
print('                                          -')
print('-   ---                                   |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     |                                    |')
print('     --------------------------------------',format(R))
print('_' *50)
time.sleep(5)
print ('-------------------------------------------------')
print ( 'PAULO ROBERTO LEAL 2020')
print ('paulorleal011291@hotmail.com')
print ('-------------------------------------------------')


