'Exemplo Priorida de processamento'
print('_'*40)
print('Exemplo Prioridade de processamento')
print ('=' * 40)
print ('5+3*2=')
import time
time.sleep(2)
n = 5+3*2 
print (n)
time.sleep(2)
print ('=' * 40)
print ('3 x 5 + 4²=')
time.sleep(2)
n2 = 3*5+4**2
print (n2)
time.sleep(2)
print ('=' * 40)
print ('3 x (5+4)² =')
n3 = 3*(5+4)**2
time.sleep(2)
print (n3)
time.sleep(2)
print ('=' * 40)
time.sleep(3)
print('Prioridade 1 () ')
time.sleep(2)
print('Prioridade 2  ** x² ')
time.sleep(2)
print('Prioridade 3  *  +  -  /  //  % ')
time.sleep(2)
print('Prioridade 4 Binario + - ')
time.sleep(2)
print ('' * 40)
print ('' * 40)
print ('_' * 40)
print ('Paulo R Leal 01 2020')
print ('paulorleal1991@hotmail.com')
print ('_' * 40)